<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="6" time="0.016">
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_001_t" time="0.0044">
    <failure type="exceptions.AssertionError">Tuples differ: (0, 0, 0, 0, 0, 0, 1, 3, 5, 2,... != (0, 0, 0, 0, 0, 0, 0, 0, 5, 0,...

First differing element 6:
1
0

- (0, 0, 0, 0, 0, 0, 1, 3, 5, 2, 4, 6)
?                    ^  ^     ^  ^

+ (0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 6)
?                    ^  ^     ^  ^

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/ubuntu/tcc/gnuradio/gr-tcc_sdr/python/qa_interleaver_bb.py", line 44, in test_001_t
    self.assertEqual(expected_result, result_data)
  File "/usr/lib/python2.7/unittest/case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 751, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 722, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 408, in fail
    raise self.failureException(msg)
    </failure>
  </testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_002_t" time="0.0020"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_003_t" time="0.0021"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_004_t" time="0.0017"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_005_t" time="0.0024"></testcase>
  <testcase classname="__main__.qa_interleaver_bb_bb" name="test_006_t" time="0.0029"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
